// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUBlvpkOkwTPfut8HLBVLK0ObcmAxxq3Y',
    appId: '1:94440346379:web:629b5ecee3380f2e03480e',
    messagingSenderId: '94440346379',
    projectId: 'flashcard-app-fe54f',
    authDomain: 'flashcard-app-fe54f.firebaseapp.com',
    storageBucket: 'flashcard-app-fe54f.firebasestorage.app',
    measurementId: 'G-N9K6MS3Q39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCQt3ZOMCKDc71oTwCieN-YR00T_veuw',
    appId: '1:94440346379:android:ff2b721c08d4cf3d03480e',
    messagingSenderId: '94440346379',
    projectId: 'flashcard-app-fe54f',
    storageBucket: 'flashcard-app-fe54f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUBlvpkOkwTPfut8HLBVLK0ObcmAxxq3Y',
    appId: '1:94440346379:web:01eed8ac71a2f77803480e',
    messagingSenderId: '94440346379',
    projectId: 'flashcard-app-fe54f',
    authDomain: 'flashcard-app-fe54f.firebaseapp.com',
    storageBucket: 'flashcard-app-fe54f.firebasestorage.app',
    measurementId: 'G-MP5XDN5XVC',
  );

}